// <auto-generated />
using System;
using LeaveRequests.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeaveRequests.Api.Migrations
{
    [DbContext(typeof(LeaveDbContext))]
    [Migration("20260916114853_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeaveRequests.Api.Entities.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewerNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeaveRequests", t =>
                        {
                            t.HasCheckConstraint("CK_LeaveRequests_DateRange", "[EndDate] >= [StartDate]");

                            t.HasCheckConstraint("Ck_LeaveRequests_Status", "[Status] IN ('Pending', 'Approved', 'Rejected')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            EndDate = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerNote = "Tasks Assigned to Employee E109 Zeyad Youssef",
                            StartDate = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved",
                            Type = "Sick"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            EndDate = new DateTime(2026, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved",
                            Type = "Vacation"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            EndDate = new DateTime(2026, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerNote = "Vacation max number of consecutive days is 7 days",
                            StartDate = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Rejected",
                            Type = "Vacation"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            EndDate = new DateTime(2026, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            Type = "Unpaid"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            EndDate = new DateTime(2026, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved",
                            Type = "Vacation"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6,
                            EndDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            Type = "Unpaid"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            EndDate = new DateTime(2026, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            Type = "Sick"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            EndDate = new DateTime(2026, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            Type = "Vacation"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            EndDate = new DateTime(2026, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved",
                            Type = "Unpaid"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 10,
                            EndDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved",
                            Type = "Unpaid"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
